// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://efqqkdzsewculejywbib.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVmcXFrZHpzZXdjdWxlanl3YmliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwMzEyNjksImV4cCI6MjA3MTYwNzI2OX0.9SKG9lV2sCQSVafZYcBMavwy9b7XAKTfGcnmXZIkOSQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});